"""Roostoo pair to Binance public-spot symbol mapping.

The mapping is infrastructure inventory, not the V2 deployment universe.
"""

BINANCE_SYMBOL_MAP: dict[str, str] = {
    "BTC/USD": "BTCUSDT",
    "ETH/USD": "ETHUSDT",
    "SOL/USD": "SOLUSDT",
    "BNB/USD": "BNBUSDT",
    "XRP/USD": "XRPUSDT",
    "DOGE/USD": "DOGEUSDT",
    "ADA/USD": "ADAUSDT",
    "AVAX/USD": "AVAXUSDT",
    "LINK/USD": "LINKUSDT",
    "DOT/USD": "DOTUSDT",
    "SUI/USD": "SUIUSDT",
    "NEAR/USD": "NEARUSDT",
    "LTC/USD": "LTCUSDT",
    "TON/USD": "TONUSDT",
    "UNI/USD": "UNIUSDT",
    "FET/USD": "FETUSDT",
    "HBAR/USD": "HBARUSDT",
    "XLM/USD": "XLMUSDT",
    "FIL/USD": "FILUSDT",
    "APT/USD": "APTUSDT",
    "ARB/USD": "ARBUSDT",
    "SEI/USD": "SEIUSDT",
    "PEPE/USD": "PEPEUSDT",
    "SHIB/USD": "SHIBUSDT",
    "FLOKI/USD": "FLOKIUSDT",
    "WIF/USD": "WIFUSDT",
    "BONK/USD": "BONKUSDT",
    "TRX/USD": "TRXUSDT",
    "ICP/USD": "ICPUSDT",
    "AAVE/USD": "AAVEUSDT",
    "WLD/USD": "WLDUSDT",
    "ONDO/USD": "ONDOUSDT",
    "CRV/USD": "CRVUSDT",
    "PENDLE/USD": "PENDLEUSDT",
    "ENA/USD": "ENAUSDT",
    "TAO/USD": "TAOUSDT",
    "POL/USD": "POLUSDT",
    "ZEC/USD": "ZECUSDT",
    "TRUMP/USD": "TRUMPUSDT",
    "EIGEN/USD": "EIGENUSDT",
    "VIRTUAL/USD": "VIRTUALUSDT",
    "CAKE/USD": "CAKEUSDT",
    "PAXG/USD": "PAXGUSDT",
}
